// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sequence/sequence.proto

package vc_pb_sequence

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqFind struct {
	Skip                 int64    `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Condition            *Model   `protobuf:"bytes,3,opt,name=condition,proto3" json:"condition,omitempty"`
	Sorts                []string `protobuf:"bytes,4,rep,name=sorts,proto3" json:"sorts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqFind) Reset()         { *m = ReqFind{} }
func (m *ReqFind) String() string { return proto.CompactTextString(m) }
func (*ReqFind) ProtoMessage()    {}
func (*ReqFind) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af5e6947b211fca, []int{0}
}

func (m *ReqFind) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqFind.Unmarshal(m, b)
}
func (m *ReqFind) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqFind.Marshal(b, m, deterministic)
}
func (m *ReqFind) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqFind.Merge(m, src)
}
func (m *ReqFind) XXX_Size() int {
	return xxx_messageInfo_ReqFind.Size(m)
}
func (m *ReqFind) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqFind.DiscardUnknown(m)
}

var xxx_messageInfo_ReqFind proto.InternalMessageInfo

func (m *ReqFind) GetSkip() int64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *ReqFind) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ReqFind) GetCondition() *Model {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *ReqFind) GetSorts() []string {
	if m != nil {
		return m.Sorts
	}
	return nil
}

type ReqCreate struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                int64    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Comments             string   `protobuf:"bytes,4,opt,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCreate) Reset()         { *m = ReqCreate{} }
func (m *ReqCreate) String() string { return proto.CompactTextString(m) }
func (*ReqCreate) ProtoMessage()    {}
func (*ReqCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af5e6947b211fca, []int{1}
}

func (m *ReqCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCreate.Unmarshal(m, b)
}
func (m *ReqCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCreate.Marshal(b, m, deterministic)
}
func (m *ReqCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCreate.Merge(m, src)
}
func (m *ReqCreate) XXX_Size() int {
	return xxx_messageInfo_ReqCreate.Size(m)
}
func (m *ReqCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCreate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCreate proto.InternalMessageInfo

func (m *ReqCreate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqCreate) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *ReqCreate) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ReqCreate) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

type DocsAndCount struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Docs                 []*Model `protobuf:"bytes,2,rep,name=docs,proto3" json:"docs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DocsAndCount) Reset()         { *m = DocsAndCount{} }
func (m *DocsAndCount) String() string { return proto.CompactTextString(m) }
func (*DocsAndCount) ProtoMessage()    {}
func (*DocsAndCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af5e6947b211fca, []int{2}
}

func (m *DocsAndCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocsAndCount.Unmarshal(m, b)
}
func (m *DocsAndCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocsAndCount.Marshal(b, m, deterministic)
}
func (m *DocsAndCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocsAndCount.Merge(m, src)
}
func (m *DocsAndCount) XXX_Size() int {
	return xxx_messageInfo_DocsAndCount.Size(m)
}
func (m *DocsAndCount) XXX_DiscardUnknown() {
	xxx_messageInfo_DocsAndCount.DiscardUnknown(m)
}

var xxx_messageInfo_DocsAndCount proto.InternalMessageInfo

func (m *DocsAndCount) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *DocsAndCount) GetDocs() []*Model {
	if m != nil {
		return m.Docs
	}
	return nil
}

type ResDocsAndCount struct {
	Status               string        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 *DocsAndCount `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ResDocsAndCount) Reset()         { *m = ResDocsAndCount{} }
func (m *ResDocsAndCount) String() string { return proto.CompactTextString(m) }
func (*ResDocsAndCount) ProtoMessage()    {}
func (*ResDocsAndCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af5e6947b211fca, []int{3}
}

func (m *ResDocsAndCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResDocsAndCount.Unmarshal(m, b)
}
func (m *ResDocsAndCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResDocsAndCount.Marshal(b, m, deterministic)
}
func (m *ResDocsAndCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResDocsAndCount.Merge(m, src)
}
func (m *ResDocsAndCount) XXX_Size() int {
	return xxx_messageInfo_ResDocsAndCount.Size(m)
}
func (m *ResDocsAndCount) XXX_DiscardUnknown() {
	xxx_messageInfo_ResDocsAndCount.DiscardUnknown(m)
}

var xxx_messageInfo_ResDocsAndCount proto.InternalMessageInfo

func (m *ResDocsAndCount) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ResDocsAndCount) GetData() *DocsAndCount {
	if m != nil {
		return m.Data
	}
	return nil
}

type ResDocs struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 []*Model `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResDocs) Reset()         { *m = ResDocs{} }
func (m *ResDocs) String() string { return proto.CompactTextString(m) }
func (*ResDocs) ProtoMessage()    {}
func (*ResDocs) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af5e6947b211fca, []int{4}
}

func (m *ResDocs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResDocs.Unmarshal(m, b)
}
func (m *ResDocs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResDocs.Marshal(b, m, deterministic)
}
func (m *ResDocs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResDocs.Merge(m, src)
}
func (m *ResDocs) XXX_Size() int {
	return xxx_messageInfo_ResDocs.Size(m)
}
func (m *ResDocs) XXX_DiscardUnknown() {
	xxx_messageInfo_ResDocs.DiscardUnknown(m)
}

var xxx_messageInfo_ResDocs proto.InternalMessageInfo

func (m *ResDocs) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ResDocs) GetData() []*Model {
	if m != nil {
		return m.Data
	}
	return nil
}

type ResDoc struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 *Model   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResDoc) Reset()         { *m = ResDoc{} }
func (m *ResDoc) String() string { return proto.CompactTextString(m) }
func (*ResDoc) ProtoMessage()    {}
func (*ResDoc) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af5e6947b211fca, []int{5}
}

func (m *ResDoc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResDoc.Unmarshal(m, b)
}
func (m *ResDoc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResDoc.Marshal(b, m, deterministic)
}
func (m *ResDoc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResDoc.Merge(m, src)
}
func (m *ResDoc) XXX_Size() int {
	return xxx_messageInfo_ResDoc.Size(m)
}
func (m *ResDoc) XXX_DiscardUnknown() {
	xxx_messageInfo_ResDoc.DiscardUnknown(m)
}

var xxx_messageInfo_ResDoc proto.InternalMessageInfo

func (m *ResDoc) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ResDoc) GetData() *Model {
	if m != nil {
		return m.Data
	}
	return nil
}

type Tracking struct {
	OptTime              string   `protobuf:"bytes,1,opt,name=optTime,proto3" json:"optTime,omitempty"`
	Operator             string   `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Action               string   `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Reason               string   `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tracking) Reset()         { *m = Tracking{} }
func (m *Tracking) String() string { return proto.CompactTextString(m) }
func (*Tracking) ProtoMessage()    {}
func (*Tracking) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af5e6947b211fca, []int{6}
}

func (m *Tracking) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tracking.Unmarshal(m, b)
}
func (m *Tracking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tracking.Marshal(b, m, deterministic)
}
func (m *Tracking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tracking.Merge(m, src)
}
func (m *Tracking) XXX_Size() int {
	return xxx_messageInfo_Tracking.Size(m)
}
func (m *Tracking) XXX_DiscardUnknown() {
	xxx_messageInfo_Tracking.DiscardUnknown(m)
}

var xxx_messageInfo_Tracking proto.InternalMessageInfo

func (m *Tracking) GetOptTime() string {
	if m != nil {
		return m.OptTime
	}
	return ""
}

func (m *Tracking) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *Tracking) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Tracking) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type Model struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value                int64       `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	Status               string      `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Comments             string      `protobuf:"bytes,5,opt,name=comments,proto3" json:"comments,omitempty"`
	Archived             bool        `protobuf:"varint,6,opt,name=archived,proto3" json:"archived,omitempty"`
	CreatedTime          string      `protobuf:"bytes,7,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	LastModTime          string      `protobuf:"bytes,8,opt,name=lastModTime,proto3" json:"lastModTime,omitempty"`
	Tracking             []*Tracking `protobuf:"bytes,9,rep,name=tracking,proto3" json:"tracking,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Model) Reset()         { *m = Model{} }
func (m *Model) String() string { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()    {}
func (*Model) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af5e6947b211fca, []int{7}
}

func (m *Model) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Model.Unmarshal(m, b)
}
func (m *Model) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Model.Marshal(b, m, deterministic)
}
func (m *Model) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Model.Merge(m, src)
}
func (m *Model) XXX_Size() int {
	return xxx_messageInfo_Model.Size(m)
}
func (m *Model) XXX_DiscardUnknown() {
	xxx_messageInfo_Model.DiscardUnknown(m)
}

var xxx_messageInfo_Model proto.InternalMessageInfo

func (m *Model) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Model) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Model) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Model) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Model) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

func (m *Model) GetArchived() bool {
	if m != nil {
		return m.Archived
	}
	return false
}

func (m *Model) GetCreatedTime() string {
	if m != nil {
		return m.CreatedTime
	}
	return ""
}

func (m *Model) GetLastModTime() string {
	if m != nil {
		return m.LastModTime
	}
	return ""
}

func (m *Model) GetTracking() []*Tracking {
	if m != nil {
		return m.Tracking
	}
	return nil
}

func init() {
	proto.RegisterType((*ReqFind)(nil), "vc.pb.sequence.ReqFind")
	proto.RegisterType((*ReqCreate)(nil), "vc.pb.sequence.ReqCreate")
	proto.RegisterType((*DocsAndCount)(nil), "vc.pb.sequence.DocsAndCount")
	proto.RegisterType((*ResDocsAndCount)(nil), "vc.pb.sequence.ResDocsAndCount")
	proto.RegisterType((*ResDocs)(nil), "vc.pb.sequence.ResDocs")
	proto.RegisterType((*ResDoc)(nil), "vc.pb.sequence.ResDoc")
	proto.RegisterType((*Tracking)(nil), "vc.pb.sequence.Tracking")
	proto.RegisterType((*Model)(nil), "vc.pb.sequence.Model")
}

func init() { proto.RegisterFile("sequence/sequence.proto", fileDescriptor_8af5e6947b211fca) }

var fileDescriptor_8af5e6947b211fca = []byte{
	// 544 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x6f, 0xd3, 0x30,
	0x18, 0x5e, 0x3e, 0xd6, 0x26, 0x6f, 0xd1, 0x40, 0x16, 0xac, 0xa1, 0x42, 0x22, 0xca, 0xa9, 0xbb,
	0x14, 0xd4, 0x71, 0xe2, 0xe3, 0xc0, 0x86, 0x90, 0x26, 0xd8, 0x26, 0x99, 0xdd, 0x38, 0x79, 0xb6,
	0x05, 0xd6, 0x5a, 0x3b, 0x8d, 0xdd, 0x4a, 0xbb, 0xf0, 0x07, 0x90, 0xf8, 0xcd, 0xc8, 0xce, 0xc7,
	0x9a, 0x92, 0x0c, 0xb8, 0xf9, 0x79, 0x3f, 0x1e, 0x3f, 0x6f, 0xde, 0xc7, 0x81, 0xb1, 0xe6, 0xab,
	0x35, 0x97, 0x94, 0xbf, 0xa8, 0x0f, 0xb3, 0xbc, 0x50, 0x46, 0xa1, 0x83, 0x0d, 0x9d, 0xe5, 0xd7,
	0xb3, 0x3a, 0x9a, 0xfd, 0x80, 0x21, 0xe6, 0xab, 0x8f, 0x42, 0x32, 0x84, 0x20, 0xd4, 0x37, 0x22,
	0x4f, 0xbc, 0xd4, 0x9b, 0x06, 0xd8, 0x9d, 0xd1, 0x63, 0xd8, 0x5f, 0x88, 0xa5, 0x30, 0x89, 0xef,
	0x82, 0x25, 0x40, 0xc7, 0x10, 0x53, 0x25, 0x99, 0x30, 0x42, 0xc9, 0x24, 0x48, 0xbd, 0xe9, 0x68,
	0xfe, 0x64, 0xd6, 0x26, 0x9e, 0x9d, 0x2b, 0xc6, 0x17, 0xf8, 0xae, 0xce, 0x52, 0x69, 0x55, 0x18,
	0x9d, 0x84, 0x69, 0x30, 0x8d, 0x71, 0x09, 0x32, 0x01, 0x31, 0xe6, 0xab, 0xd3, 0x82, 0x13, 0xc3,
	0xad, 0x02, 0x49, 0x96, 0xdc, 0x29, 0x88, 0xb1, 0x3b, 0xdb, 0xb6, 0x0d, 0x59, 0xac, 0x79, 0xad,
	0xc0, 0x01, 0x74, 0x08, 0x03, 0x6d, 0x88, 0x59, 0x6b, 0x77, 0x7d, 0x8c, 0x2b, 0x84, 0x26, 0x10,
	0x51, 0xb5, 0x5c, 0x72, 0xe9, 0xee, 0xb1, 0x99, 0x06, 0x67, 0x97, 0xf0, 0xe0, 0x83, 0xa2, 0xfa,
	0xbd, 0x64, 0xa7, 0x6a, 0x2d, 0x8d, 0x65, 0xa6, 0xf6, 0x50, 0x0d, 0x5c, 0x02, 0x74, 0x04, 0x21,
	0x53, 0x54, 0x27, 0x7e, 0x1a, 0xf4, 0x8f, 0xe5, 0x4a, 0xb2, 0xaf, 0xf0, 0x10, 0x73, 0xdd, 0xe2,
	0xbc, 0xd3, 0xe5, 0xb5, 0x74, 0xbd, 0x84, 0x90, 0x11, 0x43, 0xdc, 0x10, 0xa3, 0xf9, 0xb3, 0x5d,
	0xd6, 0x6d, 0x0e, 0xec, 0x2a, 0xb3, 0xcf, 0x76, 0x31, 0x8e, 0xbc, 0x97, 0xf4, 0xa8, 0x21, 0xbd,
	0x57, 0xaa, 0x65, 0xfb, 0x04, 0x83, 0x92, 0xed, 0x1f, 0xc8, 0xbc, 0xbf, 0x91, 0xe5, 0x10, 0x5d,
	0x15, 0x84, 0xde, 0x08, 0xf9, 0x0d, 0x25, 0x30, 0x54, 0xb9, 0xb9, 0x12, 0xcd, 0xd6, 0x6a, 0x68,
	0x57, 0xa1, 0x72, 0x5e, 0x10, 0xa3, 0x0a, 0x47, 0x1a, 0xe3, 0x06, 0x5b, 0x11, 0x84, 0x36, 0xee,
	0x89, 0x71, 0x85, 0x6c, 0xbc, 0xe0, 0x44, 0x2b, 0x59, 0x2d, 0xaf, 0x42, 0xd9, 0x4f, 0x1f, 0xf6,
	0x9d, 0x02, 0x74, 0x00, 0xbe, 0x60, 0xd5, 0x55, 0xbe, 0x60, 0x8d, 0x65, 0xfc, 0x2e, 0xcb, 0x04,
	0xdd, 0x96, 0x09, 0x7b, 0x2d, 0xb3, 0xdf, 0xb6, 0x8c, 0xcd, 0x91, 0x82, 0x7e, 0x17, 0x1b, 0xce,
	0x92, 0x41, 0xea, 0x4d, 0x23, 0xdc, 0x60, 0x94, 0xc2, 0x88, 0x3a, 0xdb, 0x32, 0x37, 0xfd, 0xd0,
	0xb5, 0x6e, 0x87, 0x6c, 0xc5, 0x82, 0x68, 0x73, 0xae, 0xca, 0x8a, 0xa8, 0xac, 0xd8, 0x0a, 0xa1,
	0x57, 0x10, 0x99, 0xea, 0x4b, 0x26, 0xb1, 0xdb, 0x62, 0xb2, 0xfb, 0xe1, 0xeb, 0x2f, 0x8d, 0x9b,
	0xca, 0xf9, 0xaf, 0x00, 0xa2, 0x2f, 0x55, 0x1e, 0xbd, 0x83, 0x41, 0xf5, 0x7a, 0x9e, 0xee, 0xb6,
	0x36, 0x0f, 0x6b, 0x72, 0xf8, 0x67, 0xca, 0x9a, 0x21, 0xdb, 0x43, 0xaf, 0x21, 0x74, 0x8f, 0x7f,
	0xdc, 0xd1, 0x6c, 0x13, 0x93, 0x71, 0x77, 0xab, 0xce, 0xf6, 0xd0, 0x5b, 0x18, 0xda, 0x92, 0x4b,
	0xc9, 0xfb, 0xdb, 0xfb, 0x6f, 0x7e, 0x03, 0x91, 0xad, 0x38, 0xb9, 0x3d, 0x63, 0xa8, 0xdb, 0x6e,
	0xf7, 0x34, 0x5f, 0xc0, 0x23, 0xdb, 0xdc, 0x7a, 0x7b, 0xbd, 0x1a, 0x9e, 0xf7, 0x8c, 0x50, 0x77,
	0xba, 0x51, 0xe2, 0x33, 0x49, 0x4f, 0x6e, 0x2f, 0xac, 0x7f, 0xfe, 0x57, 0xcd, 0xf5, 0xc0, 0xfd,
	0x5b, 0x8f, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x71, 0x84, 0x53, 0x94, 0x76, 0x05, 0x00, 0x00,
}
